//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCenterMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComputerParts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComputerParts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameCenterMVC.Resources.ComputerParts", typeof(ComputerParts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Part.
        /// </summary>
        public static string Add_Part {
            get {
                return ResourceManager.GetString("Add Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooler.
        /// </summary>
        public static string Cooler {
            get {
                return ResourceManager.GetString("Cooler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU.
        /// </summary>
        public static string GPU {
            get {
                return ResourceManager.GetString("GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDD.
        /// </summary>
        public static string HDD {
            get {
                return ResourceManager.GetString("HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeadSet.
        /// </summary>
        public static string HeadSet {
            get {
                return ResourceManager.GetString("HeadSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyBoard.
        /// </summary>
        public static string KeyBoard {
            get {
                return ResourceManager.GetString("KeyBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotherBoard.
        /// </summary>
        public static string MotherBoard {
            get {
                return ResourceManager.GetString("MotherBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MousePad.
        /// </summary>
        public static string MousePad {
            get {
                return ResourceManager.GetString("MousePad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSU.
        /// </summary>
        public static string PSU {
            get {
                return ResourceManager.GetString("PSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD.
        /// </summary>
        public static string SSD {
            get {
                return ResourceManager.GetString("SSD", resourceCulture);
            }
        }
    }
}
